conandgen/conandgen/urls.py
from django.contrib import admin
from django.urls import path, include
from convertors import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = 'index'),
    path('convert',views.convert, name = 'convert'),
    path('generators/', include('generators.urls')),
    path('textcon',views.textcon, name = 'textcon'),
    path('currencycon/',views.currencycon, name = 'currencycon'),
    path('markscon/',views.markscon, name = 'markscon'),
    path('fileconvert/',views.fileconvert, name = 'fileconvert'),
    path('thermocon/',views.thermocon, name = 'thermocon'),
    path('cryptocon/',views.cryptocon, name = 'cryptocon'),
    
]

conandgen/generators/urls.py
from django.urls import path
from . import views

app_name = 'generators'

urlpatterns = [
    
    path('',views.gensis, name = 'gensis'),
    path('password/',views.password,name='password'),
   
    
    
]

conandgen/convertors/models.py
from django.db import models

# Create your models here.
class typemodel(models.Model):

	titlename = models.CharField(max_length=100)
	discs = models.CharField(max_length=100)
	urls = models.URLField(blank = True)


	def __str__(self):
		return self.titlename

conandgen/generators/models.py
from django.db import models

# Create your models here.

conandgen/convertors/forms.py
from django import forms



class Contactform(forms.Form):
	amount = forms.IntegerField()
	category1 = forms.ChoiceField(choices=[('INR','INR || INDIA'),('USD','USD || USA'),('EUR','EUR || EURO'),('JPY','JPY || JAPANESE'),('GBP','GBP || BRITISH POUND'),('AUD','AUD || AUSTRALIAN DOLLAR'),('CAD','CAD || CANADIAN DOLLAR'),('SGD','SGD || SINGAPORE DOLLAR'),('CHF','CHF || SWISS FRANC'),('CNY','CNY || CHINESE YUAN RENMINBI ')])
	category2 = forms.ChoiceField(choices=[('INR','INR || INDIA'),('USD','USD || USA'),('EUR','EUR || EURO'),('JPY','JPY || JAPANESE'),('GBP','GBP || BRITISH POUND'),('AUD','AUD || AUSTRALIAN DOLLAR'),('CAD','CAD || CANADIAN DOLLAR'),('SGD','SGD || SINGAPORE DOLLAR'),('CHF','CHF || SWISS FRANC'),('CNY','CNY || CHINESE YUAN RENMINBI ')])

	
	# widgets = {

	# 	amount : forms.TextInput(attrs={'class':'form-control'}),
	# 	category1 : forms.Select(attrs={'class':'form-control'}),
	# 	category2 : forms.Select(attrs={'class':'form-control'}),

	# }

conandgen/convertors/views.py
import requests
from django.shortcuts import render
from .forms import Contactform
from .models import typemodel

# Create your views here.
def index(request):
	return render(request,'convertors/index.html');


def convert(request):
	typemodels = typemodel.objects.all()
	return render(request,'convertors/convert.html',{'typemodels':typemodels});

def textcon(request):
	return render(request,'convertors/text_convert.html');



def currencycon(request):
	am1 = 1
	cat1 = 'USD'
	cat2 = 'INR'
	form = Contactform(request.POST)
	if form.is_valid():

		am1 = form.cleaned_data['amount']
		cat1  = form.cleaned_data['category1']  
		cat2 = form.cleaned_data['category2']

		print(am1)





	#forms end part------------------------------------------------
	from_cur = cat1
	to_cur = cat2
	amount = am1
	url = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency='+ from_cur + '&to_currency='+to_cur +'&apikey=NNTGP21FPMMO0LMH'
	r = requests.get(url)
	r1 = r.json()
	
	cur = r1['Realtime Currency Exchange Rate']
	error_msg = ''
	if request.method == 'POST':
		error_msg = 'Default Value is shown beacuse your amount is 1 or less then 1'
		
	if amount <= 1:
		cur_rates = {
		'f_cur_name' : cur['2. From_Currency Name'],
		'f_cur_code':cur['1. From_Currency Code'],
		
		't_cur_name':cur['4. To_Currency Name'],
		't_cur_code':cur['3. To_Currency Code'],
		't_cur_rate':cur['5. Exchange Rate'],
		'time_zone':cur['7. Time Zone'],
		'bid_price':cur['8. Bid Price'],
		'ask_price':cur['9. Ask Price'],
		'f_cur_rate':amount,
		'error_msg':error_msg,

		}
		print(amount,from_cur,to_cur)
	elif amount > 1 :
		rate = cur['5. Exchange Rate']
		res = float(rate) * amount 
		cur_rates = {
		'f_cur_name' : cur['2. From_Currency Name'],
		'f_cur_code':cur['1. From_Currency Code'],
		'f_cur_rate':cur['2. From_Currency Name'],
		't_cur_name':cur['4. To_Currency Name'],
		't_cur_code':cur['3. To_Currency Code'],
		't_cur_rate':res,
		'f_cur_rate':amount,
		'time_zone':cur['7. Time Zone'],
		'bid_price':cur['8. Bid Price'],
		'ask_price':cur['9. Ask Price'],

		}
		print(res,amount,from_cur,to_cur)
	


	
	#content = typemodel.objects.all()
	cur_context = {'cur_rates':cur_rates,'form':form}
	
	
	return render(request,'convertors/currencyconvert.html',cur_context);




def markscon(request):
	
	return render(request,'convertors/marksconvert.html');


def fileconvert(request):

	return render(request,'convertors/fileconvert.html');


def thermocon(request):

	return render(request,'convertors/thermo.html');

def cryptocon(request):

	return render(request,'convertors/cryptocon.html');

conandgen/generators/views.py
from django.shortcuts import render
import random

# Create your views here.
def gensis(request):
	return render(request,"generators/genmain.html")

def password(request):

	strings = list('abcdefghijklmnopqrstuvwxyz')


	if request.GET.get('uppercase'):
		strings.extend('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
	if request.GET.get('Specialcase'):
		strings.extend('!@#$%^&*()')
	if request.GET.get('number'):
		strings.extend('0123456789')

	length = int(request.GET.get('length',12))
	thepassword = ''
	for x in range(length):
		thepassword += random.choice(strings)



	return render(request,'generators/password.html',{'password':thepassword})

conandgen/convertors/templates/convertors/convert.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'convertors/style.css'  %}">
</head>

<body>
    <header>
        <div class="container ">
            <nav class="navbar navbar-expand-lg navbar-light  ">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'convertors/CGLOGO.png'  %}" class="rounded-circle" height="50" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-5 ">
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'index' %}">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="#" >About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'convert'  %}">Convertors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'generators:gensis'  %}">Generators</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <section id="app">
        <div class="container py-5">
            <div class="card-deck ">
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/converttextimg1.1.png'  %}" class="card-img-top mt-4 p-3" alt="...">
                    <div class="card-body">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Text To Html Code</h5>
                        <p class="card-text">Quick way to convert your text data in Html format</p>
                        <a href="{% url 'textcon'  %}" class="btn btn-outline-warning rounded-pill p-2 px-3" >Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center ">
                    <img src="{% static 'convertors/currencyconvert3.jpg'  %}" class="card-img-top mt-4 p-2" alt="...">
                    <div class="card-body pt-5">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Currency Convertors </h5>
                        <p class="card-text">Quick way to analyze the real time currency exchange rate. </p>
                        <a href="{% url 'currencycon'  %}" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/Inkedmarksimg4copy1.jpg'  %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Marks Convertors</h5>
                        <p class="card-text">Quick way to find your percentage, GDP and many more. </p>
                        <a href="{% url 'markscon' %}" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container py-5">
            <div class="card-deck ">
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/fileconvert.png'  %}" class="card-img-top mt-4 p-3" alt="...">
                    <div class="card-body">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Files Convertors</h5>
                        <p class="card-text">Third party files convertors link that help you to convert your file </p>
                        <a href="{% url 'fileconvert'  %}" class="btn btn-outline-warning rounded-pill p-2 px-3" >Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center ">
                    <img src="{% static 'convertors/Inkedthermoimg_LI.jpg'  %}" class="card-img-top mt-4 p-4" alt="...">
                    <div class="card-body pt-5">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Thermo Convertors </h5>
                        <p class="card-text">Quick way to convert temperature and analyzes . </p>
                        <a href="{% url 'thermocon'  %}" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/currencyconvert1.jpg'  %}" class="card-img-top mt-4 pt-5" alt="...">
                    <div class="card-body">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Crypto Convertors</h5>
                        <p class="card-text">Quick way to analyze crypto currency . </p>
                        <a href="{% url 'cryptocon' %}" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
            </div>
        </div>

        <!----- admin  part ---------------------------------------------------->
        <div class="container py-5">
    
             <div class="row">
                {% for typemodel in typemodels %}
                <div class="col-sm-4">
            <div class="card-deck ">
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/fileconvert.png'  %}" class="card-img-top mt-4 p-3" alt="...">
                    <div class="card-body">
                        <hr>
                        <h5 class="card-title text-monospace font-italic font-weight-bold">{{ typemodel.titlename }}</h5>
                        <p class="card-text">{{ typemodel.discs }}</p>
                        <a href="{{ typemodel.urls }}" class="btn btn-outline-warning rounded-pill p-2 px-3" >Click To Convert</a>
                    </div>
                </div>
               
            </div>
        </div>
            {% endfor %}
        </div>
    </div>

    </section>
</body>

</html>

conandgen/convertors/templates/convertors/cryptocon.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'convertors/style.css'  %}">
</head>

<body>
    <header>
        <div class="container ">
            <nav class="navbar navbar-expand-lg navbar-light  ">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'convertors/CGLOGO.png'  %}" class="rounded-circle" height="50" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-5 ">
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'index' %}">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'convert'  %}">Convertors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'generators:gensis'  %}">Generators</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <section id="app">

        <div class="container py-4">
        	<h3 class="text-center text-monospace p-4  font-weight-bold bg-info mt-2 rounded">Crypto Convertor <q>Third Party Site</q></h3>
        
            <div class="card-deck pt-2 " >
                <div class="card shadow-lg  rounded text-center"  >
                    <img src="{% static 'convertors/cryptoimg.png'  %}" class="card-img-top mt-4 p-3" alt="...">
                    <div class="card-body" >
                    
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Rank 1 -- buyUcoin</h5>
                        <p class="card-text">Easy to understand and secure for investment in cryto currency.</p>
                        <a href="https://www.buyucoin.com/" target="_blank" class="btn btn-outline-warning rounded-pill p-2 px-3" @click="Conhtml()">Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center ">
                    <img src="{% static 'convertors/cryptoimg1.png'  %}" class="card-img-top mt-4 p-4" alt="...">
                    <div class="card-body pt-5">
                       
                        <h5 class="card-title text-monospace font-italic font-weight-bold">Rank 2 -- Coin DCX </h5>
                        <p class="card-text">Easy to understand and secure for investment in cryto currency. </p>
                        <a href="https://coindcx.com/" target="_blank" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
                <div class="card shadow-lg  rounded text-center">
                    <img src="{% static 'convertors/cryptoimg2.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      
                        <h5 class="card-title text-monospace font-italic font-weight-bold pt-5">Rank 3 -- WazirX</h5>
                        <p class="card-text">Easy to understand and secure for investment in cryto currency. </p>
                        <a href="https://wazirx.com/" target="_blank" class="btn btn-outline-warning rounded-pill p-2 px-3">Click To Convert</a>
                    </div>
                </div>
            </div>
        </div>
        
 
 
       
    </section>
         
</body>

</html>

conandgen/convertors/templates/convertors/currencyconvert.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <div class="container ">
            <nav class="navbar navbar-expand-lg navbar-light  ">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'convertors/CGLOGO.png'  %}" class="rounded-circle" height="50" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-5 ">
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'index' %}">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'convert'  %}">Convertors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'generators:gensis'  %}">Generators</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <section>  
    <div class="container">
        
        <h3 class="text-center text-monospace p-4  font-weight-bold bg-info mt-2 rounded">Currency Convertor</h3>
        <br>
        <div class="row ">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-4"> {% render_field form.amount class="form-control" %}</div>
                        <div class="col-sm-4"> {% render_field form.category1 class="form-control" %}</div>
                        <div class="col-sm-4">{% render_field form.category2 class="form-control" %}</div>
                    </div>
                    <div style="float: right;">
                        <button type="submit" class="btn btn-warning  rounded-pill mt-3 py-2 px-5 ">Convert Currency</button>
                    </div>
                </form>
            </div>
            <div class="col-sm-2"></div>
        </div>
        <div class="pt-5">
            <div class="row">
                <div class="col-sm-6">
                    <div class="col-">
                        <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.f_cur_rate}}</p>
                    </div>
                    <div class="col-">
                        <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.f_cur_code}} --- {{cur_rates.f_cur_name}}</p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="col-">
                        <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.t_cur_rate}}</p>
                    </div>
                    <div class="col-">
                        <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.t_cur_code}} --- {{cur_rates.t_cur_name}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4"><span class=" rounded btn-warning mx-1 p-2 justify-content-left">TimeZone</span>
                    <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.time_zone}}</p>
                </div>
                <div class="col-sm-4"><span class=" rounded btn-warning mx-1 p-2 justify-content-left">Bid Price</span>
                    <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.bid_price}}</p>
                </div>
                <div class="col-sm-4"><span class=" rounded btn-warning mx-1 p-2 justify-content-left">Ask Price</span>
                    <p class="font-weight-bold shadow p-3 text-center">{{cur_rates.ask_price}}</p>
                </div>
            </div>
        </div>
        <p class="alert-danger text-center py-4 text-monospace">{{cur_rates.error_msg}}</p>
        
    </div>
</section>
</body>

</html>

conandgen/generators/templates/generators/genmain.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <style type="text/css">
    a:hover {
        text-decoration: none;
    }

    @media only screen and (max-width: 800px) {
        .img1tag {

            margin-top: 130px;
        }

    }
    </style>
</head>

<body>
    <header>
        <div class="container ">
            <nav class="navbar navbar-expand-lg navbar-light  ">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'convertors/CGLOGO.png'  %}" class="rounded-circle" height="50" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-5 ">
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'index' %}">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'convert'  %}">Convertors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold px-4" href="{% url 'generators:gensis'  %}">Generators</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <main>
    	<div class="container pt-5">
     <h1 class="text-center text-monospace font-weight-bold font-italic">Password Generator </h1>
     <hr class="bg-danger">


<form action="{% url 'generators:password'  %}" class="border p-2 pt-5 pb-5">
	
	<select name="length">
		<option value="6">6</option>
		<option value="7">7</option>
		<option value="8">8</option>
		<option value="9">9</option>
		<option value="10">10</option>
		<option value="11">11</option>
		<option value="12">12</option>
		<option value="13">13</option>
		<option value="14">14</option>
		
	</select>
	<br>
	<br>
	<input type="checkbox" name="uppercase"> <span class="font-weight-bold text-monospace">Uppercase </span>  
	<br>
	<br>
	
	<input type="checkbox" name="Specialcase"> <span class="font-weight-bold text-monospace">SpecialCase</span>  
	<br>
	<br>
	<input type="checkbox" name="number"> <span class="font-weight-bold text-monospace">Numbers</span> 
	<br>
	<br>
<input type="submit" class="btn btn-danger " value="Generate Password">

</form> 


<a href="#" class="btn btn-primary mt-5">About Me</a>
</div>

    </main>
</body>
</html>